// Low / Medium / High risk test-case presets for the "Load Test Case" buttons
// on each scan workbench. Field keys match src/config/scanModules.js.

export const SCAN_TEST_CASES = {
  breast: {
    low: {
      age: 35,
      menopausal_status: 'pre_menopausal',
      family_history: 'none',
      palpable_lump: 'no',
      nipple_discharge: 'no',
      skin_changes: 'no',
      previous_biopsy: 'no',
      notes: 'Test case: low risk baseline.',
    },
    medium: {
      age: 45,
      menopausal_status: 'peri_menopausal',
      family_history: 'second_degree',
      palpable_lump: 'yes',
      lump_size_cm: 1.2,
      lump_location: 'upper_outer',
      nipple_discharge: 'no',
      skin_changes: 'no',
      previous_biopsy: 'yes',
      notes: 'Test case: 1 prior biopsy.',
    },
    high: {
      age: 52,
      menopausal_status: 'post_menopausal',
      family_history: 'first_degree',
      palpable_lump: 'yes',
      lump_size_cm: 2.1,
      nipple_discharge: 'no',
      skin_changes: 'no',
      previous_biopsy: 'yes',
      notes: 'Test case: 1 prior biopsy.',
    },
  },
  cervical: {
    low: {
      age: 28,
      hpv_status: 'negative',
      history_abnormal_pap: 'no',
      smoking_status: 'non_smoker',
      immunocompromised: 'no',
      cytology_class: 'Normal',
      notes: 'Test case: cytology Normal -> NILM.',
    },
    medium: {
      age: 34,
      hpv_status: 'positive',
      history_abnormal_pap: 'no',
      smoking_status: 'ex_smoker',
      immunocompromised: 'no',
      cytology_class: 'Metaplastic',
      notes: 'Test case: HPV positive (genotype unknown); cytology ASC-US -> Metaplastic.',
    },
    high: {
      age: 34,
      hpv_status: 'positive',
      history_abnormal_pap: 'yes',
      smoking_status: 'ex_smoker',
      immunocompromised: 'no',
      cytology_class: 'Parabasal',
      notes: 'Test case: HPV 16/18 positive; cytology ASC-H -> Parabasal.',
    },
  },
  pcos: {
    low: {
      age: 24,
      menstrual_regularity: 'regular',
      cycle_length_days: 28,
      clinical_symptoms: ['none'],
      amh_ng_ml: 2.5,
      lh_miu_ml: 5,
      fsh_miu_ml: 6,
      total_testosterone_ng_dl: 25,
      prolactin_ng_ml: 12,
      left_ovary_volume_ml: 6,
      left_follicle_count: 5,
      right_ovary_volume_ml: 7,
      right_follicle_count: 6,
    },
    medium: {
      age: 26,
      menstrual_regularity: 'irregular',
      cycle_length_days: 35,
      clinical_symptoms: ['acne'],
      amh_ng_ml: 4.5,
      lh_miu_ml: 8,
      fsh_miu_ml: 4,
      total_testosterone_ng_dl: 45,
      prolactin_ng_ml: 15,
      left_ovary_volume_ml: 9,
      left_follicle_count: 10,
      right_ovary_volume_ml: 10,
      right_follicle_count: 11,
    },
    high: {
      age: 26,
      menstrual_regularity: 'irregular',
      cycle_length_days: 40,
      clinical_symptoms: ['hirsutism', 'acne'],
      amh_ng_ml: 8.5,
      lh_miu_ml: 12,
      fsh_miu_ml: 4,
      total_testosterone_ng_dl: 65,
      prolactin_ng_ml: 18,
      left_ovary_volume_ml: 12,
      left_follicle_count: 14,
      right_ovary_volume_ml: 13,
      right_follicle_count: 15,
    },
  },
}

export const RISK_TIERS = [
  { key: 'low', label: 'Low Risk', emoji: '🟢' },
  { key: 'medium', label: 'Medium Risk', emoji: '🟡' },
  { key: 'high', label: 'High Risk', emoji: '🔴' },
]
